version: "3"

services:
  hadoop-master:
    image: alaeddine/hadoop-eco-system:3.3.5
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "50070:50070"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
      - "9092:9092"
      - "2181:2181"
    networks:
      - hadoop

  hadoop-slave1:
    image: alaeddine/hadoop-eco-system:3.3.5
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    ports:
      - "8040:8042"
    networks:
      - hadoop

  hadoop-slave2:
    image: alaeddine/hadoop-eco-system:3.3.5
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    ports:
      - "8041:8042"
    networks:
      - hadoop

networks:
  hadoop:
