name: Build and Push Docker Images

on:
  push:
    branches:
      - alaeddine
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} # put your DockerHub username in the repository secrets
        password: ${{ secrets.DOCKERHUB_TOKEN }} # put your DockerHub token in the repository secrets

    - name: Build and push multi-arch API Docker image with caching
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        tags: liliasfaxi/hadoop-cluster:${{ github.sha }}  # the github.sha is the commit hash
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

